name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: docker-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    uses: R0bes/devops/.github/workflows/docker-ghcr.yml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
